language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- openjdk11
notifications:
  slack:
    if: branch = master
    on_success: never
    on_failure: always
    on_start:   never
    on_cancel:  never
    on_error:   always
    secure: XSXO+5Mpd0yWhKh4zPXhsR1aK/6T9th0LCB8PgDJaiWt4LvZ4oOHsiFGhNu+gUzGjv/eX6mjZ2qEZ7EBz+1wkcI6qwWLXa2inWYUCn6E4l0BIC9MdqTlNK9wsB4TmLb99Yi9eJzyGmGA3vi6i9UetN3npG+A7ECMZeyiTqVESALGtTgRZFFSWml5VWSyCh8k2SnTyBOgEQVZivDKlL415WHbPgaH/UPYAX3X+2pmoGFqIjs7sk5CVyQ4fIg9OX2HVCVS5giT5IcqzNqZXaxrY9IZ5Ht9W2mJ2ok4wsrd1+4wx6q6BDDVI0p2PcJr+FpICjP+SI3/FWAuzqUdLkcTU7OL/Lzbf7xlcZeZuf0nFUxaAQoVCC2c9xA/cfvnNRzUZZ+aiSrDo4f8TzOEwdP/Ogk2vsET9qsCsann1VB82eMkADj/TU2eL/BHg7VyNnclKebf7gQYsTj/p/f/G+pxtIqlZlN9WF2GFzpV5yt+w/bUFZlZw5Vi6yOxmCPPAEecSeyUz+Ksokfwjt/mzG+KDPN2MJtVZucC61rVl6vDl+E2kIvjrzSHOsaSCMDcscNMym2BSltjeYUWAsoKEKtrvAxa/gijrMEUHBWHr638K6zEtcbpgPLnKh7whcbbW2+Xkd38fH3DOBmbGpVk+789N/t3l7Z1jlvSYGtcnQ7NmLg=
deploy:
  provider: script
  script: ./gradlew bintrayPublish bintrayUpload
  skip_cleanup: true
  on:
    tags: true
    branch: master

